/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthWishesRouteImport } from './routes/_auth/wishes'
import { Route as AuthAdminOrdersRouteImport } from './routes/_auth/admin/orders'
import { Route as AuthAdminOrdersNewRouteImport } from './routes/_auth/admin/orders_.new'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWishesRoute = AuthWishesRouteImport.update({
  id: '/wishes',
  path: '/wishes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminOrdersRoute = AuthAdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminOrdersNewRoute = AuthAdminOrdersNewRouteImport.update({
  id: '/admin/orders_/new',
  path: '/admin/orders/new',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/wishes': typeof AuthWishesRoute
  '/admin/orders': typeof AuthAdminOrdersRoute
  '/admin/orders/new': typeof AuthAdminOrdersNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/wishes': typeof AuthWishesRoute
  '/admin/orders': typeof AuthAdminOrdersRoute
  '/admin/orders/new': typeof AuthAdminOrdersNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_auth/wishes': typeof AuthWishesRoute
  '/_auth/admin/orders': typeof AuthAdminOrdersRoute
  '/_auth/admin/orders_/new': typeof AuthAdminOrdersNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/wishes'
    | '/admin/orders'
    | '/admin/orders/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/wishes'
    | '/admin/orders'
    | '/admin/orders/new'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/signup'
    | '/_auth/wishes'
    | '/_auth/admin/orders'
    | '/_auth/admin/orders_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/wishes': {
      id: '/_auth/wishes'
      path: '/wishes'
      fullPath: '/wishes'
      preLoaderRoute: typeof AuthWishesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/orders': {
      id: '/_auth/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthAdminOrdersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/orders_/new': {
      id: '/_auth/admin/orders_/new'
      path: '/admin/orders/new'
      fullPath: '/admin/orders/new'
      preLoaderRoute: typeof AuthAdminOrdersNewRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthWishesRoute: typeof AuthWishesRoute
  AuthAdminOrdersRoute: typeof AuthAdminOrdersRoute
  AuthAdminOrdersNewRoute: typeof AuthAdminOrdersNewRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthWishesRoute: AuthWishesRoute,
  AuthAdminOrdersRoute: AuthAdminOrdersRoute,
  AuthAdminOrdersNewRoute: AuthAdminOrdersNewRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
